# Generated by Django 2.0.3 on 2018-03-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='company',
            new_name='tinker',
        ),
    ]
